name: Build C++ Project (Optional Testing Removed)

# Define when this workflow should be triggered
on:
  push:
    branches: [ main ]  # Trigger on push events to the 'main' branch
  pull_request:
    branches: [ main ]  # Trigger on pull request events targeting the 'main' branch

# Define the jobs to be executed
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    # Define the steps to be executed for the job
    steps:
      - uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Configure CMake  # Configure CMake for the project
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build  # Build the project
        run: cmake --build ${{github.workspace}}/build --config Release
